model:
    arch: fcn3dnet
data:
    dataset: flyJanelia
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: '/Users/wonh/Desktop/flyJanelia/'
training:
    train_iters: 300000
    batch_size: 1
    patch_size:
        x: 160
        y: 160
        z: 8
    cross_entropy_ratio: 0.003
    val_interval: 1000
    n_workers: 3
    print_interval: 1
    print_interval_per_batch: False
    augmentations:
#      aug1: 'par1'
#      aug2: 'par2'
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'cross_entropy3d'
        size_average: True
    lr_schedule: 'poly_lr'
    resume: fcn3d_fly_best_model.pkl