id: 1
model:
    arch: unet3dreg_teacher
#    save_folder: '/home/heng/Desktop/Research/isbi/fly-dataset/flyJanelia/models'
data:
    dataset: flyDataset
    compound: False
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    #path: '/Users/wonh/Desktop/fly-dataset/' # for mac
    path: '/home/heng/Desktop/Research/isbi/fly-dataset/flyJanelia2' # for ubuntu
training:
    train_iters: 5 #200
    batch_size: 2
    patch_size:
        x: 160
        y: 160
        z: 8

    cross_entropy_ratio: 0.003
    val_interval: 1 #10
    n_workers: 3
    print_interval: 1
    print_interval_per_batch: False
#    augmentations: ['flip3d', 'rotate3d']
    augmentations:
      hflip3d: 0.5 # [0, 1)
      vflip3d: 0.5 # [0, 1)
      iflip3d: 0.5 # [0, 1)
      rotate3d: 180 # [-180, 180]
#      aug1: 'par1'
#      aug2: 'par2'
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 0.0005
#        momentum: 0.9
    loss:
#        name: 'cross_entropy3d'
        name: 'regression_l1'
        size_average: True
    lr_schedule:
        #name: 'poly_lr'
        #max_iter: 400
    resume: fcn3d_fly_best_model.pkl # path to the model saved before
#    resume: '/Users/wonh/y3s2/isbi/segment_3D/runs/fcn3d_fly/65461/fcn3dnet_flyJanelia_best_model.pkl' # for mac
    #resume: '/home/heng/Desktop/Research/0920/segment_3D/runs/fcn3d_fly/87793/fcn3dnet_flyJanelia_best_model.pkl' # for ubuntu